docs: add documentation for adding vocabularies using thesaurus
wetransform/hc-documentation pull request #131
Opened 2024-12-02 12:47 UTC by julia464

german and english files now contain documentation section for adding vocabularies using thesaurus

Ing-4556

2024-12-03 09:53 UTC, JohannaOtt requested changes
Thanks for documenting it, that will be very helpful for users!

2024-12-03 09:53 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Adding thesaurus keywords to the metadata can be done by defining an autofill rule in the json representation of the metadata config.
```suggestion
Adding thesaurus keywords to the metadata can be done by defining an autofill or default rule in the theme's metadata configuration.
```

2024-12-03 09:53 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +After running the autofill workflow, it might be necessary to refresh the  web page to see the string displayed in the respective fields in the UI.
```suggestion
After running the autofill workflow, it might be necessary to refresh the web page to see the string displayed in the respective fields in the UI.
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +### Hinzufügen von Thesaurus Schlüsselwörtern durch den Autofill Workflow
```suggestion
### Hinzufügen von Schlüsselwörtern mit Thesaurusangabe
```

2024-12-03 09:53 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +### Adding thesaurus keywords via autofill rule
```suggestion
### Adding thesaurus keywords
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Thesaurus Schlüsselwörter können den Metadaten zugefügt werden, indem eine entsprechenden Autofill Regel in der Json Representation der Metadaten Configuration definiert wird.
```suggestion
Schlüsselwörter mit Angabe des Thesaurus können den Metadaten zugefügt werden, indem eine entsprechende Autofill- oder Default-Regel in der Metadaten-Konfiguration des Themas definiert wird.
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Nach Ausführen des Autofill Workflows muss eventuell die Website neu geladen, damit die Änderungen auch im User Interface sichtbar sind.
```suggestion
Nach Ausführen des Autofill Workflows muss eventuell die Website neu geladen, damit die Änderungen in der Oberfläche sichtbar sind.
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Die Regel kann in Form eines Json Strings hinzugefügt werden, wobei Sonderzeichen escaped werden müssen.
```suggestion
Die Regel kann in Form eines Json-Texts hinzugefügt werden, wobei Sonderzeichen escaped werden müssen. 
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Der selbe Prozess kann auch für "defaultValue" angewendet werden.
```suggestion
Das Vorgehen kann analog auch für "defaultValue" angewendet werden.
```

2024-12-03 09:53 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Für den Fall, dass mehrere Schlüsselwörter definiert werden sollen, müssen eckige Klammern um die Json Strings gesetzt werden. (see [Hinzufügen mehrerer Autofill-Regeln für ein Metadatenfeld](#hinzuf
```suggestion
Für den Fall, dass mehrere Schlüsselwörter definiert werden sollen, müssen eckige Klammern um die Json-Texte gesetzt werden. (siehe [Hinzufügen mehrerer Autofill-Regeln für ein Metadatenfeld](#hinzuf%C3%BCgen-mehrerer-autofill-regeln-f%C3%BCr-ein-metadatenfeld)).
```

2024-12-03 16:19 UTC, julia464 commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Für den Fall, dass mehrere Schlüsselwörter definiert werden sollen, müssen eckige Klammern um die Json Strings gesetzt werden. (see [Hinzufügen mehrerer Autofill-Regeln für ein Metadatenfeld](#hinzuf
Thanks for the feedback! I updated accordingly.

2024-12-04 08:17 UTC, florianesser commented
@julia464 Thanks a lot for the PR. I've added an additional with some editorial changes and an update how the code block is included (using ```json instead of indent)

2024-12-04 08:21 UTC, florianesser commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Für den Fall, dass mehrere Schlüsselwörter definiert werden sollen, müssen eckige Klammern um die Json Strings gesetzt werden. (see [Hinzufügen mehrerer Autofill-Regeln für ein Metadatenfeld](#hinzuf
@JohannaOtt @julia464 I'd prefer `JSON-Strings` as `JSON-Texte` doesn't really fit IMO. If we want to translate `String`, it would be `JSON-Zeichenfolge`.

2024-12-04 10:22 UTC, florianesser approved these changes
From my side, good to be merged

2024-12-05 13:36 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Für den Fall, dass mehrere Schlüsselwörter definiert werden sollen, müssen eckige Klammern um die Json Strings gesetzt werden. (see [Hinzufügen mehrerer Autofill-Regeln für ein Metadatenfeld](#hinzuf
> I'd prefer JSON-Strings

Fine with me.

2024-12-05 13:40 UTC, JohannaOtt approved these changes
Some minor changes, but please decide yourself if you want to add them. More cosmetic changes than needed.
As they are not blockers for putting it online, I still approve the PR.

2024-12-05 13:40 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +### Hinzufügen von Thesaurus-Schlüsselwörtern mit Thesaurusangabe
```suggestion
### Hinzufügen von Schlüsselwörtern mit Thesaurusangabe
```

2024-12-05 13:40 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Adding thesaurus keywords to the metadata can be done by defining an `autofillRule` or `defaultValue` in the theme's metadata configuration. The autofill rule can be added as a JSON string with speci
```suggestion
Adding thesaurus keywords to the metadata can be done by defining an `autofillRule` or `defaultValue` in the theme's metadata configuration. The autofill rule can be added as a JSON string with special characters escaped. After running the autofill workflow for a related dataset, it might be necessary to refresh the web page to see the string displayed in the respective fields in the UI.
```

2024-12-05 13:40 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Schlüsselwörter mit Angabe des Thesaurus können den Metadaten zugefügt werden, indem eine entsprechende Autofill-Regel (`autofillRule`) oder ein Default-Wert (`defaultValue`) in der Metadaten-Konfigu
```suggestion
Schlüsselwörter mit Angabe eines Thesaurus können den Metadaten zugefügt werden, indem eine entsprechende Autofill-Regel (`autofillRule`) oder ein Default-Wert (`defaultValue`) in der Metadaten-Konfiguration des Themas definiert wird. Die Regel kann in Form eines JSON-Strings hinzugefügt werden, wobei Sonderzeichen mit einen Backslash (`\`) maskiert werden müssen. Nach Ausführen des Autofill-Workflows für zugehörigen Datensätze muss eventuell die Seite im Browser neu geladen werden, damit die Änderungen in der Oberfläche sichtbar sind.
```

2024-12-06 13:04 UTC, merged