Remove arcgis, enter END
wetransform/hc-documentation pull request #35
Opened 2022-09-22 17:38 UTC by thorsten-reitz

2022-09-23 06:47 UTC, stempler commented on src/pages/index.js
> +      INSPIRE, ALKIS, XPlanGML, SOSI, eCH, WFD, FFH, Natura2000, CDDA, and END.
Same text can be found here - not sure what the difference is: https://github.com/wetransform/hc-documentation/blob/f6452abb239628d99584e89ef5a3f74b58f59bef/src/pages/index.js#L31

I think this is where the German version lives: https://github.com/wetransform/hc-documentation/blob/f6452abb239628d99584e89ef5a3f74b58f59bef/i18n/de/code.json#L298

2022-09-23 08:55 UTC, morch23mj requested changes

2022-09-23 08:55 UTC, morch23mj commented on src/pages/index.js
> +      INSPIRE, ALKIS, XPlanGML, SOSI, eCH, WFD, FFH, Natura2000, CDDA, and END.
@thorsten-reitz as @stempler mentioned, [hc-documentation/src/pages/index.js](https://github.com/wetransform/hc-documentation/blob/f6452abb239628d99584e89ef5a3f74b58f59bef/src/pages/index.js#L31) and [hc-documentation/i18n/de/code.json](https://github.com/wetransform/hc-documentation/blob/f6452abb239628d99584e89ef5a3f74b58f59bef/i18n/de/code.json#L298) are the relevant files to update.

The description attribute could be then removed.

2022-09-28 11:58 UTC, thorsten-reitz commented on src/pages/index.js
> +      INSPIRE, ALKIS, XPlanGML, SOSI, eCH, WFD, FFH, Natura2000, CDDA, and END.
Thanks for the pointer, should be fixed now.

2022-09-28 12:32 UTC, morch23mj approved these changes
LGTM

2022-09-28 12:52 UTC, florianesser commented on i18n/de/code.json
> +    "message": "hale»connect ist das weltweit beste Software-as-a-Service-Tool für die agile, datengetriebene Design und Implementierung von mehr als 5.000 offenen Standards wie INSPIRE, ALKIS, XPlan
@thorsten-reitz 

"Software-as-a-Service-Tool für die agile, datengetriebene Design und Implementierung" sounds wrong (die Design?)

There's a superfluous space after "CDDA": `Natura2000, CDDA , und END`

2022-12-06 08:22 UTC, merged