feat: DE ETF, md only, source config and DE-EN map viewer update added.
wetransform/hc-documentation pull request #59
Opened 2023-04-12 13:03 UTC by Kate-Lyndegaard

This PR contains the German translation of ETF, md-only and source config documentation updates. I also included an update to the map viewer in both English and German.

2023-04-14 08:31 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +hale»connect unterstützt derzeit die Erstellung von Datensatz-Metadaten, ohne dass zugehörige Daten hochgeladen werden müssen. Der Workflow „Nur Metadaten“ ist für Service-Metadaten nicht verfügbar.
hale»connect unterstützt die Erstellung von Datensatz-Metadaten, ohne dass zugehörige Daten hochgeladen werden müssen. Der Workflow „Nur Metadaten“ ist nur für Datensatz-Metdaten verfügbar, nicht für Service-Metadaten.

2023-04-14 08:34 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +## Nur-Metadaten-Design erstellen ##
## 'Nur-Metadaten'-Thema konfigurieren ##

2023-04-14 08:35 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +Um ein Nur-Metadaten-Design zu erstellen, folgen Sie diesem Arbeitsablauf als angemeldeter Datenmanager oder Designmanager:
Um ein 'Nur-Metadaten'-Thema zu erstellen, folgen Sie diesem Arbeitsablauf als angemeldeter Datenmanager oder Themenmanager:

2023-04-14 08:43 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +
1. Gehen Sie zu &laquo;Themen&raquo; auf der Hauptsymbolleiste
2. Gehen Sie zu &laquo;Neues Thema erstellen&raquo; am Ende der Themenliste
3. Wählen Sie im Schritt &laquo;Basisthema auswählen&raquo; „Nicht übernehmen“, um ein Thema zu erstellen, das nicht auf einem bereits existierenden Thema basiert.
     * Dadurch wird ein leeres Thema ohne zugeordnete Funktionstypen erstellt.
4. Geben Sie als Thementyp &laquo;Benutzerdefiniert&raquo;  an und vergeben Sie einen Namen für Ihr Thema. Fügen Sie bei Bedarf eine Beschreibung und Versionsnummer hinzu.
5. Im nächsten Schritt &laquo;Objektart&raquo; hinzufügen, akzeptieren Sie die Standardeinstellung und klicken Sie auf &laquo;Weiter&raquo;.
6. Klicken Sie im letzten Schritt auf &laquo;Anlegen&raquo;.

Das neu erstellte Thema wird nun angezeigt. Der Toggle *Nur Metadaten veröffentlichen* auf der Themenübersichtsseite muss aktiviert sein. 

Navigieren Sie zum Abschnitt Metadaten des Themas, um die Datensatz-Metadaten zu konfigurieren. Weitere Informationen zum Konfigurieren von Metadaten finden Sie auf der Seite [Metadatenkonfiguration bearbeiten](../../setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata).

2023-04-14 08:53 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +6. Erstellen und veröffentlichen Sie im letzten Schritt Ihre Metadaten.
[...]
2. Gehen Sie zu &laquo;Neuen Datensatz anlegen&raquo; am Ende der Datensatzliste
3. Wählen Sie Ihr 'Nur-Metadaten'-Thema aus, um es als Basiskonfiguration für Ihren neuen Datensatz zu verwenden.
4. Geben Sie Ihrer Metadatendatei einen Namen. Dieser Name soll es Ihnen ermöglichen, die Metadaten im System schnell und eindeutig zu identifizieren.
5. Geben Sie im nächsten Schritt alle verbleibenden Metadatenwerte ein, die für die Veröffentlichung erforderlich sind. 
6. Erstellen und veröffentlichen Sie im letzten Schritt Ihre Metadaten

@Kate-Lyndegaard It seems that the functionality for adding metadata URL is not working properly (why do I have to add URL twice ?) and furthermore it should be described in more detail already in the theme configuration section ?

2023-04-14 09:05 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/map-preview/2014-01-02-map-preview.md
## Das Layer-Widget ##
Das Layer-Widget enthält 
- Legendeninformationen, 
- die Option zum Ein- und Ausschalten von Layern und 
- die Option zum Filtern von Raster-Datensätzen für die Anzeige innerhalb einer Datensatzserie. 

### Auswahl von Einzeldatensätzen einer Datensatzserie ###
Klicken Sie für veröffentlichte Datensatzseriendienste auf das Filtersymbol im Layer-Widget, um den Datensatzauswahldialog aufzurufen und Teildatensätze für die Anzeige auszuwählen. 

### Benutzerdefinierten WMS als Hintergrundkarte hinzufügen ###
Das Layer-Widget bietet auch die Möglichkeit, eine benutzerdefinierte Hintergrundkarte per URL bereitzustellen. Für mehr Informationen zum Hinzufügen einer Hintergrundkarte zu ihrer Organisation, lesen sie [diesen Abschnitt der Dokumentation](../../users-roles-orgs/manage-orgs/2015-03-01-users-edit-organisation.md). 

### Externen WMS als Hintergrundkarte hinzufügen ###
Darüber hinaus unterstützt das Layer-Widget die Option, externe WMS-Dienste zur Kartenvorschau hinzuzufügen, sodass neben den hale»connect-Diensten auch externe Dienste angezeigt werden können. Die Konfiguration erfolgt in den Einstellungen zur Organisation unter Angabe eines WMS im Bereich &laquo;Karten-Konfiguration&raquo;.

2023-04-14 09:06 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/map-preview/2014-01-02-map-preview.md
Maybe a link to the doc section https://help.wetransform.to/docs/users-roles-orgs/manage-orgs/2015-03-04-users-add-organisation would be helpful for section "Externen WMS als Hintergrundkarte hinzufügen"

2023-04-14 09:21 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-07-reference-data-download-services.md
> +
### Validierungsberichte ###
Das &laquo;Validierungsberichte&raquo;-Feld enthält eine Ergebnisliste für eine Reihe von Tests, die für veröffentlichte Metadaten und Dienste ausgeführt wurden. 
Klicken Sie auf das Download-Symbol, um den Validierungsbericht direkt herunterzuladen. Grüne Häkchen zeigen an, dass der Validierungsbericht (ETF-Bericht) gültig ist. Rote Xs weisen auf Fehler oder einen nicht ausgeführten Test hin. 

Benutzer können die Validierungsprüfung (ETF-Tests) für alle aufgelisteten Ressourcen erneut ausführen, indem sie auf die Schaltfläche «Alle Tests ausführen» klicken. Alternativ können Benutzer einen einzelnen Test erneut ausführen, indem sie auf das kreisförmige Pfeilsymbol neben dem Download-Symbol klicken. 
Das gelbe Warnsymbol wird für Ressourcen mit Konformitätsklassen angezeigt, die manuelle Überprüfungen erfordern

@Kate-Lyndegaard Do we or should we explain "Konformitätsklassen" somewhere ? Maybe a new "Schlüsselkonzept: Validieurng" ?

2023-04-14 09:27 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-07-reference-data-download-services.md
>  Im &laquo;Diensteinstellungen&raquo;-Feld können sie mit Hilfe des Schalters die Koordinatenachsen ihres Datensatzes tauschen. Wenn ihr Datensatz mit vertauschten Koordinaten angezeigt wird, veränder
Im &laquo;Diensteinstellungen&raquo;-Feld können sie mit Hilfe des Schalters &laquo;Koordinatenreihenfolge tauschen&raquo;- die Koordinatenachsen ihres Datensatzes tauschen. 

Diese Funktion ist sinnvoll, wenn ihr Datensatz mit vertauschten Koordinaten angezeigt wird und führt dazu, das die Darstellung in der Kartenanzeige korrigiert wird.

@Kate-Lyndegaard Does it also influence the WFS and ATOM in any way

2023-04-14 09:28 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-07-reference-data-download-services.md
>  Im &laquo;Diensteinstellungen&raquo;-Feld können sie mit Hilfe des Schalters die Koordinatenachsen ihres Datensatzes tauschen. Wenn ihr Datensatz mit vertauschten Koordinaten angezeigt wird, veränder
I know you didn't edit this section but I just saw it..

2023-04-14 09:55 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-08-reference-data-view-services.md
> +Eine Reihe von standardmäßigen Konformitätsklassen wird auf Dataset-Metadaten ausgeführt, Service-Metadaten und Services heruntergeladen und angezeigt und kann im Design konfiguriert werden. Tests pr
### Konfiguration der Validierungstests ###

Die Metadaten werden basierend auf standardisierten Konformitätsklassen validiert. Welche das sind, kann im &laquo;Thema&raquo; im Bereich &laquo;Validierung&raquo; konfiguriert werden. Die Tests prüfen die INSPIRE-Konformität Ihrer Datensätze und Dienste.
Die Anzahl und Art der Tests, die auf Ihre Metadaten und Dienste angewendet werden, spiegeln Ihre Compliance-Anforderungen wieder. Weitere Informationen finden Sie unter [Validierung konfigurieren](../../setup-hc/config-validation/2015-02-10-validation.md).

2023-04-14 09:56 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-08-reference-data-view-services.md
> +## Auf Metadaten und Darstellungs-Diensten ausgeführte Tests: ##
## Auf Metadaten und Darstellungs-Dienste ausgeführte Validierungstests: ##

2023-04-14 10:00 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
> +Das &laquo;Inhalt&raquo;-Feld enthält Angaben zum Datenvolumen der zum Datensatz gehörenden Dateien, die verwendeten Kapazitätspunkte, die Anzahl der im Datensatz enthaltenen Objekte und das dem Date
Das &laquo;Inhalt&raquo;-Feld enthält folgende Angaben:
- Datenvolumen der zum Datensatz gehörenden Dateien, 
- verwendete Kapazitätspunkte, 
- Anzahl der im Datensatz enthaltenen Objekte und 
- das dem Datensatz zugeordnete Thema.

2023-04-14 10:00 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
>  Das &laquo;Eigentümerschaft&raquo;-Feld gibt an, für welche Organisation ein Datensatz angelegt wurde, welche oder welcher Nutzende den Datensatz angelegt hat, wann der Datensatz erstellt und wann er
Das &laquo;Eigentümerschaft&raquo;-Feld gibt an, 
- für welche Organisation ein Datensatz angelegt wurde, 
- welche oder welcher Nutzende den Datensatz angelegt hat, 
- wann der Datensatz erstellt und 
- wann er zuletzt aktualisiert wurde.

2023-04-14 10:05 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
> +Das &laquo;Status&raquo;-Feld ermöglicht einen Überblick über die Ressourcen, die zu einem Datensatz vorliegen. Sind diese mit einem Haken in einem grünen Kreis gekennzeichnet, sind sie valide und kö
Das &laquo;Status&raquo;-Feld bietet einen Überblick über alle Ressourcen, die zum Datensatz gehören:

- Der Haken in grünem Kreis zeigt an, das die Ressource valide ist und regulär genutzt werden kann.
- Das Ausrufezeichen in gelbem Kreis zeigt Validierungswarnungen an. Bei der Nutzung der Ressource im System können Fehler auftreten. 
- Das X in einem roten Kreis zeigt Validierungsfehler an. Die Ressource kann im System nicht planmäßig genutzt werden. 
- Ein Strich in einem grauen Kreis bedeutet, dass die entsprechende Ressource nicht veröffentlicht ist.

2023-04-14 10:11 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
> +Die Spalte „Validierungsberichte“ im Statusbereich enthält eine Reihe von herunterladbaren ETF-Testergebnissen und einen Dateianalysebericht der Quelldaten. Das Datensatz-Download-Symbol ermöglicht e
Die Spalte „Validierungsberichte“ enthält eine Reihe von herunterladbaren ETF-Testergebnissen und einen Dateianalysebericht der Quelldaten. 

Im Bericht werden die Ergebnisse der Prüfung gegen die im Thema konfigurierten Datensatz-Konformitätsklassen dokumentiert. Des weiteren erfolgt eine Bewertung der Gültigkeit der Datei basierend auf der anfänglichen Dateianalyse, die während des Datenuploads durchgeführt wurde. 
Alle während der ETF-Validierung oder Dateianalyse aufgetretenen Fehler werden im Bericht in der Spalte „Validierungsdetails“ aufgelistet.

Der Dateianalysebericht wird in der Sprache erstellt, die in den Spracheinstellungen der Website ausgewählt wurde.

2023-04-14 10:17 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
> +Die anklickbaren Dokumentsymbole rufen einen Dialog auf, um den ETF-Bericht für die Ressource herunterzuladen und zu verwalten. Grüne Häkchen zeigen an, dass der ETF-Bericht gültig ist. Rote Xs weise
### Details zum Status der Validierungsberichte ###
Klickt man auf die Dokumentsymbole wird ein kleiner Dialog geöffent, um zum einen den Validierungsbericht für die Ressource herunterzuladen und zum anderen diesen zu verwalten. 
Grüne Häkchen zeigen an, dass der ETF-Bericht gültig ist. 
Rote Xs weisen auf Fehler oder einen nicht ausgeführten Test hin. 

Benutzer können die Validierungstests für eine bestimmte Ressource oder alle Ressourcen in einer Kategorie erneut ausführen, indem sie auf die Schaltfläche «Alle Tests ausführen» klicken. Alternativ können Benutzer einen einzelnen Test ausführen, indem sie auf das kreisförmige Pfeilsymbol neben dem Download-Symbol klicken. 
Das gelbe Warnsymbol wird für Ressourcen mit Konformitätsklassen angezeigt, die manuelle Überprüfungen erfordern.

@Kate-Lyndegaard Does the second section fit in here ?

2023-04-14 10:20 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/themes/2018-04-01-reference-themes-tasks.md
> +Der &laquo;Aufgaben&raquo;-Bereich ermöglicht es ihnen, mit dem Thema verbundene Aufgaben anderen Benutzenden zuzuweisen. Klicken sie in das Feld oberhalb der gepunkteten Linie, um einen Aufgabentite
### Aufgaben ###
Der &laquo;Aufgaben&raquo;-Bereich ermöglicht es ihnen, mit dem Thema verbundene Aufgaben anderen Benutzenden zuzuweisen. 
Klicken sie in das Feld oberhalb der gepunkteten Linie, um einen Aufgabentitel festzulegen. Die Aufgabe speichert automatisch ihren Erstellungszeitpunkt, ihren Status und durch wen sie erstellt wurde. Klicken sie auf das Aufklappmenü neben &laquo;Bearbeiter&raquo; um jemandem die Bearbeitung der Aufgabe zuzuweisen. 
Nutzen sie das &laquo;Beschreibung&raquo;-Feld um eine Beschreibung der Aufgabe und alle für die Bearbeitung der Aufgabe relevanten Informationen bereitzustellen.

2023-04-14 10:23 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/themes/2018-04-03-reference-themes-datasetseries.md
>  Der &laquo;Datensatz-Reihe&raquo;-Bereich ermöglicht es ihnen, das Anlegen von Datensatz-Reihen zu aktivieren. Eine Datensatz-Reihe ist eine Sammlung von Datensätzen, denen dieselbe Spezifikation zug
## Datensatz-Reihe ##

2023-04-14 10:23 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/themes/2018-04-03-reference-themes-datasetseries.md
## Datensatz-Reihe ##

2023-04-14 10:33 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/config-source-data/2015-02-10-database.md
> +Um ein leeres Design zu erstellen, folgen Sie diesem Arbeitsablauf als angemeldeter Datenmanager oder Designmanager:
m ein leeres Thema zu erstellen, folgen Sie diesem Arbeitsablauf als angemeldeter Datenmanager oder Designmanager:

2023-04-14 10:34 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/config-source-data/2015-02-10-database.md
> +6. Klicken Sie im letzten Schritt auf &laquo;Erstellen&raquo;.
1. Gehen Sie zu &laquo;Themen&raquo; auf der Hauptsymbolleiste
2. Gehen Sie zu &laquo;Neues Thema erstellen&raquo; am Ende der Themenliste
3. Wählen Sie „Nicht erben“, um ein Thema zu erstellen, das nicht auf einem bereits vorhandenen Thema basiert.
     * Dadurch wird ein leeres Thema ohne zugeordnete Funktionstypen erstellt.
4. Geben Sie einen Namen für Ihr Thema ein. Fügen Sie bei Bedarf eine Beschreibung und Versionsnummer hinzu.
5. Im nächsten Schritt Feature-Typen hinzufügen, akzeptieren Sie die Standardeinstellung und klicken Sie auf &laquo;Weiter&raquo;.
6. Klicken Sie im letzten Schritt auf &laquo;Erstellen&raquo;.

2023-04-14 10:38 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/config-validation/2015-02-10-validation.md
> +Die Validierungskonfiguration definiert die Konformitätsklassen, die für alle Datensätze ausgeführt werden, die einem Design zugeordnet sind. Eine Konformitätsklasse ist eine Reihe von Anforderungen,
Die Validierungskonfiguration definiert die Konformitätsklassen, die für alle Datensätze ausgeführt werden, die einem Thema zugeordnet sind. 
Eine Konformitätsklasse besteht aus einer Reihe von Anforderungen, die in einem Standard definiert sind und mit einer ausführbaren Testsuite (ETS) getestet werden. 
Alle INSPIRE-Konformitätsklassen, die für hale»connect-Ressourcen gelten, stehen zur Auswahl. Die Validierungskonfiguration ist mit dem Standardsatz von Konformitätsklassen vorbelegt, die zum Testen von INSPIRE-Ressourcen verwendet werden. 
Wenn Sie ein neues Thema erstellen, wird eine Standardvalidierungskonfiguration bereitgestellt. Themenmanager und Superuser können Konformitätsklassen zur Validierungskonfiguration hinzufügen oder daraus entfernen. 
Klicken Sie auf die Schaltfläche «Liste löschen», um alle Konformitätsklassen zu entfernen. 
Klicken Sie auf die Schaltfläche «Standardeinstellungen hinzufügen», um zur Standardkonfiguration zurückzukehren. Deaktivieren Sie den Schalter, um die Validierung zu deaktivieren.

2023-04-14 10:40 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/config-validation/2015-02-10-validation.md
> +1. Gehen Sie zu &laquo;Designs&raquo;
1. Gehen Sie zu &laquo;Themen&raquo;

2023-04-14 10:41 UTC, Claudia-WE requested changes
Hi Kate,
see my comments below

2023-04-17 07:41 UTC, Kate-Lyndegaard commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +6. Erstellen und veröffentlichen Sie im letzten Schritt Ihre Metadaten.
@Claudia-WE Thank you for your feedback. What do you mean by: "why do I have to add URL twice?"

2023-04-17 08:06 UTC, Kate-Lyndegaard commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-07-reference-data-download-services.md
> +
@Claudia-WE I will add a new section with a definition of conformance class.

2023-04-17 12:56 UTC, Kate-Lyndegaard commented
@Claudia-WE I have added all of your feedback. I would appreciate your re-review.

2023-04-17 17:41 UTC, Claudia-WE commented on docs/create-manage-datasets/map-preview/2014-01-02-map-preview.md
> +    * Legend Informationen,
Legend Information

2023-04-17 17:41 UTC, Claudia-WE commented on docs/create-manage-datasets/map-preview/2014-01-02-map-preview.md
> +    * the option to filter raster datasets for display withint a dataset series
the option to filter raster datasets for display within a dataset series

2023-04-17 17:42 UTC, Claudia-WE commented on docs/create-manage-datasets/map-preview/2014-01-02-map-preview.md
> +# Externen WMS als Hintergrundkarte hinzufügen #
Add external WMS as background map

2023-04-17 17:45 UTC, Claudia-WE commented on docs/key-concepts/2015-05-01-terms-conformance-class.md
> +a resource to determine if the resource meets all of the requirements of the conformance class.
a standard specification resource to determine if a certain hale connect resource meets... 

@Kate-Lyndegaard maybe more concrete ?

2023-04-17 17:51 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/create-manage-datasets/create-metadata/2015-01-10-metadata-create.md
> +6. Erstellen und veröffentlichen Sie im letzten Schritt Ihre Metadaten.
When I go through the creation process I have to add the metadata url twice: First in processing step "Datenquelle festlegen" and once again in step 5 "Datensatz-Metadaten" URL eingeben"

Maybe it is ok - but I was stumbling over it

2023-04-17 17:52 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-07-reference-data-download-services.md
> +
Nice

2023-04-17 17:55 UTC, Claudia-WE commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-11-reference-data-overview.md
> +
30-35 and 37-38 are now redundant from my point of view

2023-04-17 18:00 UTC, Claudia-WE requested changes
@Kate-Lyndegaard Did a second review row - please be aware that there was one part redundant and one section kept in German instead of change to English. Otherwise I would have chosen Approve. 
I am not totally familiar with git - thus I just hope that you can merge now although I selected Request changes ?

2023-04-18 06:52 UTC, Kate-Lyndegaard commented on docs/create-manage-datasets/map-preview/2014-01-02-map-preview.md
> +# Externen WMS als Hintergrundkarte hinzufügen #
@Claudia-WE I am just trying to teach people German :-)

2023-04-18 06:55 UTC, Kate-Lyndegaard commented on docs/key-concepts/2015-05-01-terms-conformance-class.md
> +a resource to determine if the resource meets all of the requirements of the conformance class.
@Claudia-WE You can't say "standard specification resource" and you cannot really say "a compliant resource" because that is what the test is testing- whether or not a generic resource is, in fact, compliant.

2023-04-18 06:58 UTC, Kate-Lyndegaard commented
@Claudia-WE Those were good catches. Thank you for your re-review. I have made the fixes.

2023-04-19 13:05 UTC, Claudia-WE approved these changes

2023-04-19 13:50 UTC, merged