hale»connect API documentation
wetransform/hc-documentation pull request #71
Opened 2023-11-16 11:40 UTC by Kate-Lyndegaard

This PR adds documentation about the hale»connect API and how to use it.

ING-4009

2023-11-16 12:16 UTC, morch23mj reviewed
LGTM. Will the German translation be added in this PR as well? If so, it can be done under the same folder tree in `i18n/de/docusaurus-plugin-content-docs/current/`.

2023-11-17 09:58 UTC, stempler commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +For on-premise users, enter: https://[yourdomain]/swagger/
Depends on if they have enabled it.

2023-11-17 09:58 UTC, stempler commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +A bucket is a container for objects stored in Amazon S3. The hale»connect bucket service APIs provide access to files and datasets associated with each resource type.
Maybe more general referring to "file storage" instead of "Amazon S3"? The internals don't really matter for the API and depending on the setup AWS is not used.

2023-11-17 09:58 UTC, stempler commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +### Notification service
I would maybe leave this one out. There aren't really any useful endpoints for end users I think.

2023-11-17 09:58 UTC, stempler commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The workflow manager service enables users to access information about ETF Validator and Spatineo monitoring. The generic workflows.....????
The workflow manager is responsible for managing most tasks in the platform like transformations, validation, status updates etc.

2023-11-17 14:33 UTC, morch23mj commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Enter this URL in your favorite browser: https://haleconnect.com/swagger/
Maybe include a general note for the whole document: `Throughout the document _https://haleconnect.com_ is used as domain, but replace it with your own custom domain if you have one.`

2023-11-20 09:24 UTC, Kate-Lyndegaard commented
@stempler @morch23mj I added your feedback.

2023-11-20 09:30 UTC, JohannaOtt requested changes
Generally LGTM, I left some comments.
Would it maybe make sense to also quickly introduce the different types of requests (POST, GET,...) that can be made? Not sure if users not used to swagger yet would know where to start/what to do right away even if they know which service is serving for what.

2023-11-20 09:30 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
A series permit -> a series permits ?

2023-11-20 09:30 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
> To begin exploring the hale»connect API, it is necessary to log-in using your hale»connect user name and password, in Swagger.
Is it really necessary to use/log in to swagger? We do use many API calls to update resources on the platform etc. without using swagger.

2023-11-20 09:30 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +### Resources
For the other services the headline is XXX service - so maybe "resource service"?

2023-11-20 09:30 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +### Reports
reports service?

2023-11-20 09:40 UTC, Kate-Lyndegaard commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
@JohannaOtt 
A series of access URLs (plural subject) = permit (plural verb conjugation)

Can you provide a description of other ways you use the hc apis? Or what you would like added here?

2023-11-20 09:42 UTC, Kate-Lyndegaard commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +### Resources
@JohannaOtt 
The other URLs are actually named XXX service in [this document](https://github.com/wetransform/hale-connect-dev/blob/master/defaults/hc.yml). I am taking the names directly from here. I can add "service" to them, but that is not how they are named in this document.

2023-11-20 09:44 UTC, Kate-Lyndegaard commented
> Generally LGTM, I left some comments. Would it maybe make sense to also quickly introduce the different types of requests (POST, GET,...) that can be made? Not sure if users not used to swagger yet would know where to start/what to do right away even if they know which service is serving for what.

@JohannaOtt I will add a section about the different types of requests.

2023-11-20 09:47 UTC, morch23mj approved these changes

2023-11-20 10:29 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
That is interesting, thanks for explaining. In German, it would be singular verb conjugation because it is only 1 series.


> Can you provide a description of other ways you use the hc apis?

Some examples of using API calls without swagger are for example available in [this](https://app.getguru.com/card/TLkKE6dc/HOWTO-Upload-data-to-haleconnect-using-the-API) and [this](https://app.getguru.com/card/ck8Mn64i/API-description-for-RIVM-END-Workflow) guru card and many more are used in the [update tool box](https://github.com/wetransform/jira-updater/tree/master) we are using in the service team. I assume there are also endpoints available for all of them in swagger (not sure at all though)?

2023-11-20 10:30 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +### Resources
Ok, then it is probably expected as it is. Did not know that document

2023-11-20 11:03 UTC, Kate-Lyndegaard commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
> Some examples of using API calls without swagger are for example available in [this](https://app.getguru.com/card/TLkKE6dc/HOWTO-Upload-data-to-haleconnect-using-the-API) and [this](https://app.getguru.com/card/ck8Mn64i/API-description-for-RIVM-END-Workflow) guru card and many more are used in the [update tool box](https://github.com/wetransform/jira-updater/tree/master) we are using in the service team. I assume there are also endpoints available for all of them in swagger (not sure at all though)?

@stempler I have a few questions:

Should curl instructions be added here, or to a separate page about using the hc api with curl? 

Are all endpoints listed in the guru cards also available in Swagger? 

Does the hc api support any HTTP operations beyond [GET](https://datatracker.ietf.org/doc/html/rfc9110#name-get), [POST](https://datatracker.ietf.org/doc/html/rfc9110#name-post), [PUT](https://datatracker.ietf.org/doc/html/rfc9110#name-put) and [DELETE](https://datatracker.ietf.org/doc/html/rfc9110#name-delete)? These are the only 4 I can see in Swagger....

2023-11-21 09:42 UTC, stempler commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The hale»connect platform can be accessed via API. The hale»connect API enables users to automatically execute workflows, change configuration settings, manage organisations and users, and many other
> Should curl instructions be added here, or to a separate page about using the hc api with curl?

Swagger will show a curl example why trying out a request. Generally I think we should focus on the Swagger/OpenAPI documentation for details and not maintain something else in addition.

> Are all endpoints listed in the guru cards also available in Swagger?

Usually yes. There may be some exceptions.
The documentation in the Guru cards probably adds some more information about what the endpoints do any what they are for.

2023-11-22 08:53 UTC, JohannaOtt approved these changes
I left some minor spelling/wording comments. Overall LGTM

2023-11-22 08:53 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Select Login, and provide your hale»connect user name and password to obtain an authentication token. If the Login endpoint is not visible, enter https://haleconnect.com/accounts/swagger.yaml in the
at the tope - at the top?

2023-11-22 08:53 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +The POST operation requests that a server accept data contained in the request.
accept - accepts?

2023-11-22 08:53 UTC, JohannaOtt commented on docs/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +When working in Swagger, we recommend examining the endpoint, the HTTP operation and the written description of the endpoint available for each entry.
we - wetransform? Not sure if we are usually using first person in the documentation.

2023-11-22 12:03 UTC, Kate-Lyndegaard commented
@JohannaOtt OK, great. I added the last changes.

2023-11-22 13:22 UTC, merged