feat: hc-api documentation in German is added
wetransform/hc-documentation pull request #73
Opened 2023-11-29 09:48 UTC by Kate-Lyndegaard

ING-4009

2023-11-29 12:54 UTC, JohannaOtt requested changes

2023-11-29 12:54 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Geben sie für On-Premise-Kunden Folgendes ein:: https://[yourdomain]/swagger/
Geben sie für On-Premise-Kunden Folgendes ein --> Für On-Premise-Kunden muss die URL wie folgt angepasst werden

2023-11-29 12:54 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Um Aufgaben über die API auszuführen und auf zusätzliche hale»connect API-URLs zuzugreifen, ist ein gültiges Authentifizierungstoken erforderlich. Klicken sie auf die Schaltfläche &laquo;Try it out!&
hale»connect API-URLs --> hale»connect-API-URLs
und kopieren Sie das --> und kopieren sie das
hale»connect API-URL --> hale»connect-API-URL

2023-11-29 12:54 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Der Schema-Dienst gewährt Zugriff auf Schemas und Profile und ermöglicht Benutzende die Durchführung von Aktionen im Zusammenhang mit Schema-Speicherorten, Namespaces und Feature-Typen.
ermöglicht Benutzende --> ermöglicht Benutzenden

2023-11-29 12:54 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Der Workflow-Manager-Dienst verwaltet die meisten Aufgaben auf der Plattform, einschließlich Transformationen, Validierung und Statusaktualisierungen. Der Workflow-Manager-Dienst ermöglicht Benutzend
ermöglicht Benutzende -> ermöglicht Benutzenden

2023-11-29 12:54 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Mit dem Aktionsdienst können Benutzer eine Organisation löschen und die Standardgrundkarte einer Organisation abrufen.
können Benutzer --> können Benutzende

2023-11-30 08:17 UTC, Kate-Lyndegaard commented
@JohannaOtt I added all of your feedback. Thank you.

2023-11-30 08:33 UTC, JohannaOtt requested changes
Found more Sie/sie occurrences I did not see in the first place unfortunately.

2023-11-30 08:33 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Der Zugriff auf die hale»connect-Plattform ist über eine API möglich. Die hale»connect API ermöglicht es Benutzenden, Workflows automatisch auszuführen, Konfigurationseinstellungen zu ändern, Organis
müssen Sie sich mit Ihrem hale»connect-Benutzernamen -> müssen sie sich mit ihrem hale»connect-Benutzernamen

2023-11-30 08:33 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/haleconnect-api/2023-11-15-haleconnect-api.md
> +Geben sie diese URL in Ihren Browser ein: https://haleconnect.com/swagger/
in Ihren Browser -> in ihren Browser

2023-11-30 08:45 UTC, Kate-Lyndegaard commented
@JohannaOtt OK, no problem. I fixed those.

2023-11-30 09:05 UTC, JohannaOtt approved these changes
LGTM

Just a general note on the commits: I think formally, the fixup commits should be squashed into the original commit by rebasing the branch. Not sure how restrictive this repository should be handled but in other repositories of ours, we would not accept that.

2023-11-30 10:23 UTC, merged