feat: token auth documentation is added in German
wetransform/hc-documentation pull request #74
Opened 2023-11-30 11:21 UTC by Kate-Lyndegaard

ING-4125

2023-11-30 11:44 UTC, morch23mj approved these changes

2023-12-01 08:50 UTC, JohannaOtt requested changes

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Der Abschnitt &laquo;Zugriffskontrolle&raquo; definiert, wie auf veröffentlichte hale»connect-Dienste zugegriffen werden kann. hale»connect unterstützt sichere Serviceanfragen durch den Einsatz von A
Schalten sie &laquo;Authentifizierung mit Organisations-Token&raquo; um --> Aktivieren sie &laquo;Authentifizierung mit Organisations-Token&raquo;

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Der Abschnitt &laquo;Zugriffskontrolle&raquo; definiert, wie auf veröffentlichte hale»connect-Dienste zugegriffen werden kann. hale»connect unterstützt sichere Serviceanfragen durch den Einsatz von A
Darstellungs- und Download-Dienste können separat konfiguriert werden. --> I do not really understand what that means here. Separate from each other?

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Authentifizierungstoken können auf der Profilseite der Organisation generiert werden. Klicken sie auf die Schaltfläche &laquo;Token generieren&raquo;. Klicken sie auf die Schaltfläche, um ein Authent
Klicken sie auf die Schaltfläche &laquo;Token generieren&raquo;. Klicken sie auf die Schaltfläche, um ein Authentifizierungstoken zu generieren. --> Klicken sie auf den Knopf &laquo;Token generieren&raquo;., um ein Authentifizierungstoken zu generieren.

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Es kann auch ein einfacher Passwortschutz aktiviert werden. Der grundlegende Passwortschutz ist nicht so sicher wie die Token-Authentifizierung. Schalten sie &laquo;Basic Authentifizierung mit festem
Schalten sie &laquo;Basic Authentifizierung mit festem Benutzernamen und Passwort&raquo; um --> Aktivieren sie  &laquo;Basic Authentifizierung mit festem Benutzernamen und Passwort&raquo;

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Es kann auch ein einfacher Passwortschutz aktiviert werden. Der grundlegende Passwortschutz ist nicht so sicher wie die Token-Authentifizierung. Schalten sie &laquo;Basic Authentifizierung mit festem
erfordert der Zugriff auf Dienste, dass ein Benutzende einen Benutzernamen und ein Kennwort eingibt. --> müssen Benutzende für den Zugriff auf Dienste Nutzername und Passwort eingeben.

2023-12-01 08:50 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/references/data/2018-03-09-reference-data-accesscontrol.md
> +Änderungen an Zugriffskontrollen erfordern, dass Dienste erneut veröffentlicht werden, damit sie wirksam werden.
Änderungen an Zugriffskontrollen erfordern, dass Dienste erneut veröffentlicht werden, damit sie wirksam werden. --> Damit Änderungen an Zugriffskontrollen wirksam werden, müssen die Dienste erneut publiziert werden.

2023-12-04 09:09 UTC, Kate-Lyndegaard commented
@JohannaOtt OK, great. I have added all of your feedback.

2023-12-04 10:07 UTC, merged