feat: schema update tutorial is added
wetransform/hc-documentation pull request #88
Opened 2024-05-29 13:24 UTC by Kate-Lyndegaard

This PR includes a tutorial aimed at helping users update their hale studio transformation projects and associated resources on hale connect.

2024-05-31 09:00 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +A transformation project is a [hale»studio](https://www.wetransform.to/products/halestudio/) project using the formats \*.halex or \*.halez that has been uploaded to hale»connect. The project contain
```suggestion
An online transformation project is a [hale»studio](https://www.wetransform.to/products/halestudio/) project using the formats \*.halex or \*.halez that has been uploaded to hale»connect. The project contains references to source and target schemas, an alignment that defines the transformation by mapping elements from the source schema to elements in the target schema, additional configuration for the loaded schemas and configuration options for the desired output.
```

2024-05-31 09:01 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +The next step is to update the schema used in the transformation project.
```suggestion
The next step is to update the schema used in the transformation project, so that it uses the INSPIRE Protected Site schema in version 5.0 instead of 4.0.
```

2024-05-31 09:02 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +In this step, we will load the source data and complete the steps displayed in the cell entity matching dialogs that appear in hale»studio. Cell entity matching dialogs appear when a schema is change
```suggestion
In this step, we will load the source data and complete the steps displayed in the cell entity matching dialogs that appear in hale»studio. Cell entity matching dialogs appear when a schema is changed and hale»studio cannot determine how to update the existing mappings due to changed type or property names or changed namespaces as in this case. In these cases, the end user must provide hale»studio information on how to update the existing mappings, based on the new schema.
```

2024-05-31 09:02 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +It is useful to review the changes that have been made to the schema you are updating to obtain an overview of the elements that need to be updated.
```suggestion
It is useful to review the changes that have been made to the schema you are updating to obtain an overview of the elements that need to be updated. The changes are for example documented as comments in the INSPIRE xsd schema files available [here](https://inspire.ec.europa.eu/schemas/index.html)
```

2024-05-31 09:06 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +Once the source data is loaded, a potentially large number of cell entity dialogs will appear successively until all elements have been updated to reflect the new schema. A complete update requires t
```suggestion
Once the source data is loaded, a potentially large number of cell entity dialogs will appear successively until all elements have been updated to reflect the new schema. A complete update requires the end user to manually select the element in the element tree that hale»studio is searching for, for each updated reference. In some cases, hale»studio will correctly identify the matching element in the new schema (for example if only the namespace changed but the type and property name remain the same), in other cases, direct user input is required.
```

2024-05-31 09:06 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +**Step 4: Check validation and save transformtion project**
```suggestion
**Step 4: Check validation and save transformation project**
```

2024-05-31 09:08 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +
I wonder if we should add an info here that in case of very complex schema changes, the dialog can also be skipped for specific cases (not sure what the button name is - something like none?) and then be handled explicitely and manually once all dialogues are worked through.
To make it clear that in case the user does not know how to handle one specific case, the whole re-mapping is not blocked but they can continue with the remaining ones.

2024-05-31 09:09 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +### **Updating an Online Transformation Workflow on hale»connect**
Same question on the uppercase words as above.

2024-05-31 09:11 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +   * Add information. Provide the name, author, type and version of your schema. Ensure that you select INSPIRE as type from the dropdown menu. When you are finished, click &laquo;Continue&raquo;
> Ensure that you select INSPIRE as type from the dropdown menu

Not sure if we should explicitely mention that here. IIRC, it does not really have useful implementations currently.

2024-05-31 09:12 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +The next step is to update the Feature Types section of your INSPIRE Protected Sites 4.0 theme to use the feature types from the INSPIRE Protected Sites 5.0 schema.
```suggestion
The next step is to update the Feature Types section of your INSPIRE Protected Sites theme to use the feature types from the INSPIRE Protected Sites 5.0 schema.
```

2024-06-03 07:49 UTC, Kate-Lyndegaard commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +**Step 1: Open an existing transformation project in hale»studio**
Originally I had described this approach, however in testing I realized that when you load an online transfo in hale studio you cannot use the Reload and update schemas functionality as Simon confirmed here: https://wetransform.slack.com/archives/C06JBBH0CTA/p1716978756517289

2024-06-03 07:49 UTC, Kate-Lyndegaard commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +### **Updating an Online Transformation Project**
These are the rules for English titles: https://editorsmanual.com/articles/capitalizing-headings/

2024-06-03 07:56 UTC, Kate-Lyndegaard commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +
@JohannaOtt Thank you for the feedback. I think that manually editing the hale config files is an advanced and complex topic which is prone to error and that would be difficult for many users. It is also not the topic of this tutorial and would require further explanation in perhaps a second tutorial. I am happy to add an additional comment here, but please add the specific wording you would like added to avoid any further back-and-forth.

2024-06-03 12:18 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +### **Updating an Online Transformation Project**
Ok, thanks. See comment above - I would remove the "Online" as we are not looking into that any longer

2024-06-03 12:18 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +A transformation project is a [hale»studio](https://www.wetransform.to/products/halestudio/) project using the formats \*.halex or \*.halez that has been uploaded to hale»connect. The project contain
Taking this back, as it is not about online transformations - see above

2024-06-04 09:17 UTC, Kate-Lyndegaard commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +*IMPORTANT: The target dataset is automatically generated by the online transformation workflow. The target dataset is typically transformed, INSPIRE GML.*
Removed.

2024-06-05 13:42 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +must be re-transformed using an updated transformation project to be compliant against the latest version of the schema. Breaking changes have also been introduced to v4.0 schemas, although no major
No, I mean between line 11 and 12. I think it is one sentence that should simply continue in the same line.

2024-06-05 13:44 UTC, JohannaOtt requested changes

2024-06-05 13:44 UTC, JohannaOtt commented on docs/tutorials/2018-04-28-schema-update-tutorial.md
> +It is useful to review the changes that have been made to the schema you are updating to obtain an overview of the elements that need to be updated.  The changes are documented as comments in the INS
```suggestion
It is useful to review the changes that have been made to the schema you are updating to obtain an overview of the elements that need to be updated. The changes are documented as comments in the INSPIRE \*.xsd schema files available [here](https://inspire.ec.europa.eu/schemas/index.html).
```

2024-06-06 15:05 UTC, JohannaOtt approved these changes
LGTM

2024-06-10 06:53 UTC, merged