feat: service profile documentation is added.
wetransform/hc-documentation pull request #99
Opened 2024-09-16 11:14 UTC by Kate-Lyndegaard

ING-4407

I did not add documentation for the service profile entitled: 'Conventions of GDI-DE' because I cannot determine that it does anything in service or dataset metadata, set in service or dataset configuration sections, in DE or ENG md. If we cannot clarify what it does, I think we can remove it.

Once the English version of this update is agreed on, I will go ahead with the DE translation.

2024-09-26 10:28 UTC, Kate-Lyndegaard commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +hale»connect service metadata profiles provide options for adding and removing additional metadata elements in the hale»connect auto-generated metadata. Service profiles are available in the dataset
OK, will do.

2024-09-26 10:52 UTC, Kate-Lyndegaard commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +hale»connect service metadata profiles provide options for adding and removing additional metadata elements in the hale»connect auto-generated metadata. Service profiles are available in the dataset
Originally I took the name out of the json:` "name": "md-service.profiles"`

2024-09-26 11:17 UTC, Kate-Lyndegaard commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +          Nařízení Komise (ES) č. 1205/2008 ze dne 3. prosince 2008, kterým se provádí směrnice Evropského parlamentu a Rady 2007/2/ES týkající se metadat, část D 4, Klasifikace služeb prostorových d
Added it in English.

2024-10-02 08:03 UTC, JohannaOtt requested changes
@florianesser Will you take working on the requested change over now?

2024-10-02 08:03 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +**Configuring service profiles**
```suggestion
**Configuring metadata profiles**
```

According to what has been discussed [here](https://github.com/wetransform/hc-documentation/pull/99#discussion_r1776797534)

2024-10-11 06:00 UTC, florianesser commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +**Configuring service profiles**
Changed

2024-10-11 08:00 UTC, florianesser commented
@JohannaOtt I added the German translation now. In that context, I also did another editorial pass on the English version and did some further changes. They are in their own commits so that you can review them separately.

2024-10-15 06:09 UTC, florianesser commented
@JohannaOtt As the sprint is ending today, I will merge the changes now. In case you have more feedback, just send it to me and I will incorporate it in a follow-up PR, thanks!

2024-10-15 06:12 UTC, merged

2024-10-16 12:13 UTC, JohannaOtt reviewed
@florianesser I found some things that should be changed IMO. Added respective comments.

2024-10-16 12:13 UTC, JohannaOtt commented on docs/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +This profile enables use of the term `information` in the `transferOptions` element in the WFS Capabilities document.  The term `information` is found in the code list `CI_OnLineFunctionCode`. Sectio
Additional whitespace after first sentence.

2024-10-16 12:13 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +hale»connect-Metadatenprofile bieten Optionen für das Hinzufügen und Entfernen zusätzlicher Metadatenelemente in den von hale»connect automatisch generierten Metadaten. Metadatenprofile sind in den K
IMO, the comma before "und" needs to be removed but there might be a special rule I am not aware of.

2024-10-16 12:13 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Diese Option ermöglicht die Verwendung des Wertes `information` im Element `transferOptions` im WFS-Capabilities-Dokument. Der Wert "information" ist Teil der Codeliste `CI_OnLineFunctionCode`. Im Ab
in dem der WFS GetCapabilities den Wert download verwendet --> in dem das WFS-Capabilities-Dokument den Wert 'download' verwendet?

Der Standardwert von hale "connect ist download --> Der Standardwert von hale»connect ist 'download'

2024-10-16 12:13 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Dieses Profil aktiviert die Verwendung eines `gmx:Anchor`-Elements für die Quellenreferenz im Element `gmd:thesaurusName` und für die Referenzierung des Diensttyp-Schlüsselworts aus der Codelist `Spa
Codelist --> Codeliste
The "an" at the end of the last sentence is superfluous.

2024-10-16 12:13 UTC, JohannaOtt commented on i18n/de/docusaurus-plugin-content-docs/current/setup-hc/edit-metadata-config/2015-02-10-theme-edit-metadata.md
> +Der Zweck dieses Metadatenprofils ist es, Benutzern, die GDI-DE-konforme Metadaten erzeugen möchten, die Möglichkeit zu geben, dies mit Hilfe eines einzigen Profils zu tun. Es wird in diesem Fall emp
Benutzern --> Nutzenden